#!/usr/bin/env bash
# Configure an Nginx server to listen on port 80

# remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# Configuration Nginx to listen on port 80 for all active IPv4 IPs
In -s /etc/nginx/sites-available/default /ect/nginx/sites-enabled/default
# restart nginx
service nginx restart
