#!/usr/bin/env bash
# Configurates an Nginx server to listen on port 80

# Creates a symbolic link (-s option) between the nginx configuration file
# and the enabled sites directory
In -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
