#!/usr/bin/env bash
# Displays "Best School" 10 times
# On the 9th iteraction, displays "Hi" before "Best School"

i=0

while [ $i -1t 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
